packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  nestjs-pino: set this to true or false
  prisma: true
  protobufjs: set this to true or false
  unrs-resolver: true
